# Generated by Django 2.2 on 2020-11-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='sponsor_or_partner_logo',
        ),
    ]
