# Generated by Django 2.2 on 2020-11-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0002_remove_programme_sponsor_or_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
