# Generated by Django 2.2 on 2020-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0003_programme_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='link_to_program',
            field=models.URLField(blank=True, null=True),
        ),
    ]
