# Generated by Django 2.2 on 2020-11-05 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0004_programme_link_to_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='programme_type',
            field=models.CharField(choices=[('TRAINING', 'TRAINING'), ('COMPETITION', 'COMPETITION'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('OPPORTUNITY', 'OPPORTUNITY')], help_text='select programme type', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='programme_benefited_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edo.Programme'),
        ),
    ]
