# Generated by Django 2.2 on 2020-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0005_auto_20201105_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
