# Generated by Django 2.2 on 2020-11-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0006_testimony_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='link_address_4_start_ups',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
