# Generated by Django 2.2 on 2020-11-06 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0007_auto_20201106_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
