# Generated by Django 2.2 on 2020-11-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0009_gallery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='Photo_Gallery'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='Photo_Gallery'),
        ),
    ]
