# Generated by Django 2.2 on 2020-11-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0010_auto_20201106_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='devotion',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='caption_picture',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
