# Generated by Django 2.2 on 2020-11-06 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0011_auto_20201106_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
    ]
