# Generated by Django 2.2 on 2020-11-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0013_team_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='linkedin',
            new_name='link_to_your_linkedin_account',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter',
            new_name='link_to_your_twitter_account',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='phone_number',
            new_name='link_to_your_whatsapp_number',
        ),
    ]
