# Generated by Django 2.2 on 2020-11-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0014_auto_20201106_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
