# Generated by Django 2.2 on 2020-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0015_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
