# Generated by Django 2.2 on 2020-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0016_auto_20201110_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.TextField(help_text='word limit', max_length=700),
        ),
    ]
