# Generated by Django 2.2 on 2020-11-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0019_auto_20201110_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='whatsapp_number',
            field=models.IntegerField(default='+123', help_text='phone number in International formart without the plus e.g (2348012345...)'),
        ),
    ]
