# Generated by Django 2.2 on 2020-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0021_auto_20201123_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='photo_type',
        ),
        migrations.AddField(
            model_name='gallery',
            name='photo_type',
            field=models.CharField(choices=[('Gallery', 'Gallery'), ('HUB', 'HUB'), ('Sartups', 'Sartups')], default='Board_mambers', max_length=20),
            preserve_default=False,
        ),
    ]
