# Generated by Django 2.2 on 2020-11-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0022_auto_20201123_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='office',
            field=models.CharField(choices=[('aws_instructors', 'aws_instructors'), ('Borad_members', 'Borad_members'), ('others', 'others')], default='Board_mambers', max_length=20),
            preserve_default=False,
        ),
    ]
