# Generated by Django 2.2 on 2020-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0023_team_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='programme_benefited_from',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
