# Generated by Django 2.2 on 2020-11-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0024_auto_20201123_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='date_to',
        ),
    ]
