# Generated by Django 2.2 on 2020-11-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0025_auto_20201126_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='link_address_4_start_ups',
            new_name='start_up_Instagram_link',
        ),
        migrations.AddField(
            model_name='gallery',
            name='start_up_facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='start_up_linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='start_up_twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='start_up_website_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='testimony',
            field=models.TextField(help_text='word limit of 800', max_length=800),
        ),
    ]
