# Generated by Django 2.2 on 2020-11-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0027_gallery_start_up_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='start_up_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
