# Generated by Django 2.2 on 2020-12-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0030_auto_20201127_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='caption_picture',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_photo',
            field=models.ImageField(blank=True, null=True, upload_to='news author photo'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_post_picture',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='connect',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo_type',
            field=models.CharField(choices=[('Gallery', 'Gallery'), ('HUB', 'HUB'), ('StartUps', 'StartUps'), ('halls', 'halls')], max_length=20),
        ),
    ]
