# Generated by Django 2.2 on 2020-12-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0031_auto_20201204_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_post_picture',
            new_name='caption_picture',
        ),
    ]
