# Generated by Django 2.2 on 2021-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0034_auto_20210121_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='NOTE: word limit of 350', max_length=350)),
                ('photo', models.ImageField(upload_to='Photo_Gallery')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='Photo_Gallery')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='Photo_Gallery')),
                ('publish', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='please leave this field blank', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='halls',
        ),
        migrations.AddField(
            model_name='startupsdandhubs',
            name='category',
            field=models.CharField(choices=[('start_up', 'start_up'), ('hub', 'hub')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.TextField(help_text='NOTE: word limit of 350', max_length=350),
        ),
        migrations.AlterField(
            model_name='startupsdandhubs',
            name='about',
            field=models.TextField(help_text='NOTE: word limit of 350', max_length=350),
        ),
    ]
