# Generated by Django 2.2 on 2021-01-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0035_auto_20210121_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='description',
            field=models.TextField(help_text='NOTE: word limit of 200 for the overview'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='description',
            field=models.TextField(help_text='NOTE: word limit of 200 for the overview'),
        ),
        migrations.AlterField(
            model_name='startupsdandhubs',
            name='about',
            field=models.TextField(help_text='NOTE: word limit of 200 for the overview'),
        ),
        migrations.AlterField(
            model_name='startupsdandhubs',
            name='category',
            field=models.CharField(choices=[('start_up', 'start_up'), ('hub', 'hub')], max_length=10, null=True),
        ),
    ]
