# Generated by Django 2.2 on 2021-01-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edo', '0037_auto_20210125_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='application_link',
            field=models.URLField(blank=True, help_text='link to google form or any other application link', null=True),
        ),
    ]
