# Generated by Django 2.2 on 2020-11-14 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pageslider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='slide_images')),
                ('caption_top_title_small', models.CharField(blank=True, max_length=100, null=True)),
                ('caption_mid_title_large', models.CharField(max_length=100)),
                ('top_slider_animation_gesture', models.CharField(choices=[('fadeInUp', 'fadeInUp'), ('zoomIn', 'zoomIn'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'), ('slideInUp', 'slideInUp'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'), ('lightSpeedIn', 'lightSpeedIn'), ('lightSpeedOut', 'lightSpeedOut'), ('flipInY', 'flipInY'), ('flipInX', 'flipInX')], max_length=100)),
                ('caption_buttom_title_small', models.CharField(blank=True, max_length=100, null=True)),
                ('bottom_slider_animation_gesture', models.CharField(choices=[('fadeInUp', 'fadeInUp'), ('zoomIn', 'zoomIn'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'), ('slideInUp', 'slideInUp'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'), ('lightSpeedIn', 'lightSpeedIn'), ('lightSpeedOut', 'lightSpeedOut'), ('flipInY', 'flipInY'), ('flipInX', 'flipInX')], max_length=100)),
                ('slider_button_animation_gesture', models.CharField(choices=[('fadeInUp', 'fadeInUp'), ('zoomIn', 'zoomIn'), ('fadeInDown', 'fadeInDown'), ('fadeInLeft', 'fadeInLeft'), ('fadeInRight', 'fadeInRight'), ('slideInDown', 'slideInDown'), ('slideInLeft', 'slideInLeft'), ('slideInRight', 'slideInRight'), ('slideInUp', 'slideInUp'), ('bounceInDown', 'bounceInDown'), ('bounceInLeft', 'bounceInLeft'), ('bounceInRight', 'bounceInRight'), ('bounceInUp', 'bounceInUp'), ('lightSpeedIn', 'lightSpeedIn'), ('lightSpeedOut', 'lightSpeedOut'), ('flipInY', 'flipInY'), ('flipInX', 'flipInX')], max_length=100)),
                ('button_caption', models.CharField(max_length=10)),
                ('publish', models.BooleanField(default=False)),
                ('select_page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='decor.Page')),
            ],
        ),
    ]
