# Generated by Django 2.2 on 2020-11-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageslider',
            name='select_page',
            field=models.CharField(choices=[('home', 'home'), ('aws_page', 'aws_page')], default='home', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
