# Generated by Django 2.2 on 2021-01-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decor', '0002_auto_20201114_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageslider',
            name='button_caption',
            field=models.CharField(max_length=20),
        ),
    ]
